(function(root,factory){const api=factory(typeof module==='object'?require('./mechanics.js'):root.Mechanics);if(typeof module==='object')module.exports=api;else root.Curriculum=api;})(globalThis,function(M){
  'use strict';
  const fmt=v=>Number(v.toFixed(3)).toLocaleString('fr-FR');
  // Keep structured cells for the UI and a readable, multiline text for exports.
  function withMatrix(key,before,symbol,values,unit='',after=''){
    const rows=values.map(row=>row.map(v=>typeof v==='number'?fmt(v):v));
    const matrixText=`${symbol} =\n${rows.map(row=>'[ '+row.join('  ')+' ]').join('\n')}${unit?' '+unit:''}`;
    return {[key]:[before,matrixText,after].filter(Boolean).join('\n'),[key+'Matrix']:{before,symbol,rows,unit,after}};
  }
  const chapters=[
    {title:'Lire la matière',subtitle:'Contraintes & matrices',badge:'Œil de mécanicien',icon:'σ',time:'10 min',
      lesson:'<p>Imagine une coupe dans une tôle soudée. La matière de l’autre côté exerce une force par unité de surface : le vecteur contrainte <b>t = σ · n</b>, où n est la normale unitaire à la coupe.</p><p>Dans σ<sub>ij</sub>, i est la direction de la force et j celle de la normale. La diagonale porte les contraintes normales ; hors diagonale, on trouve les cisaillements. En mécanique classique sans couples volumiques, <b>σ<sub>ij</sub> = σ<sub>ji</sub></b> : six composantes indépendantes en 3D.</p><p>Traction positive, compression négative. 1 MPa = 1 N/mm². Une force en kN se multiplie par 1 000 avant de la diviser par une section en mm².</p>',...withMatrix('formula','','σ',[['σx','τxy','τxz'],['τxy','σy','τyz'],['τxz','τyz','σz']])},
    {title:'Changer de regard',subtitle:'Coupe & rotation',badge:'Pilote des repères',icon:'↗',time:'15 min',
      lesson:'<p>Un même état mécanique prend différentes composantes quand on tourne le repère. La normale x′ fait un angle θ positif antihoraire avec x ; y′ est à +90° de x′. On prend <b>n = (cos θ, sin θ)</b> et m = (−sin θ, cos θ).</p><p>Calcule t = σn, puis σn = n·t et τ = m·t. Ce τ signé est la composante dans la direction y′ sur la face de normale x′. Tourner le repère ne change ni la trace ni les contraintes principales.</p><p>Dans notre tracé, τ est positif vers le haut : une rotation physique +θ parcourt le cercle de <b>−2θ</b>. D’autres livres inversent l’axe τ ; vérifie toujours la convention.</p>',formula:'σx′ = C + D cos 2θ + τxy sin 2θ\nτx′y′ = −D sin 2θ + τxy cos 2θ\nC = (σx + σy)/2 ; D = (σx − σy)/2'},
    {title:'Tracer le cercle',subtitle:'Mohr & directions principales',badge:'Cartographe de Mohr',icon:'◯',time:'15 min',
      lesson:'<p>Le point A(σx, τxy) et le point B(σy, −τxy) sont les extrémités d’un diamètre. Le centre vaut C et le rayon R. Les intersections avec l’axe normal donnent les deux valeurs principales <b>dans le plan</b>.</p><p>La normale à la direction de σmax est à θp = ½ atan2(2τxy, σx−σy), modulo 180°. Sur cette face, le cisaillement est nul. Si R = 0, toutes les directions du plan sont principales.</p><p>Le rayon est le cisaillement maximal dans le plan. En contraintes planes, il faut ensuite ajouter σz = 0 et trier les trois valeurs pour trouver le maximum absolu en 3D.</p>',formula:'R = √[ ((σx−σy)/2)² + τxy² ]\nσmax,min du plan = C ± R'},
    {title:'Mesurer la déformation',subtitle:'ε, γ & rosettes',badge:'Gardien du facteur 2',icon:'ε',time:'15 min',
      lesson:'<p>Aux petites déformations, le tenseur ε décrit les allongements et changements d’angles. Attention : son terme hors diagonale est <b>εxy = γxy/2</b>. γxy est le cisaillement d’ingénieur, exprimé en radians.</p><p>Le cercle des déformations se trace dans (ε, γ/2). Le rayon représente εxy maximal ; le cisaillement d’ingénieur maximal dans le plan vaut donc <b>2R</b>. Les déformations en µε se divisent par un million avant de calculer des contraintes.</p><p>Une rosette 0°/45°/90° donne εx = ε0, εy = ε90 et γxy = 2ε45−ε0−ε90. On suppose des jauges au même point, température compensée et petites déformations.</p>',...withMatrix('formula','','ε',[['εx','γxy/2'],['γxy/2','εy']],'','εθ = Cε + Dε cos 2θ + (γxy/2) sin 2θ')},
    {title:'Relier σ et ε',subtitle:'Hooke & bridage',badge:'Mécanicien élastique',icon:'⇄',time:'20 min',
      lesson:'<p>Pour un matériau élastique linéaire isotrope, E relie contrainte et déformation ; ν décrit la contraction transversale. Dans le jeu : E = 210 000 MPa et ν = 0,30, sauf indication contraire.</p><p>En <b>contraintes planes</b>, σz = 0 mais εz = −ν(σx+σy)/E peut être non nul. En <b>déformations planes</b>, εz = 0 et, sans déformation thermique, σz = ν(σx+σy).</p><p>Une dilatation libre vaut αΔT. Un bridage axial total impose εtotale = 0 et donc σx = −EαΔT, tant que le modèle reste élastique. Un cycle réel de soudage implique des gradients, de la plasticité et parfois des transformations métallurgiques : cette relation seule ne prédit pas les contraintes résiduelles finales.</p>',formula:'εx = [σx − ν(σy + σz)]/E\nG = E/[2(1+ν)] ; γxy = τxy/G'},
    {title:'Passer en trois dimensions',subtitle:'Tricercle & invariants',badge:'Explorateur 3D',icon:'◎',time:'20 min',
      lesson:'<p>Diagonalise le tenseur symétrique et trie les valeurs <b>σ1 ≥ σ2 ≥ σ3</b>. Les trois cercles correspondent aux paires (1,3), (1,2) et (2,3). Le plus grand rayon vaut (σ1−σ3)/2.</p><p>Chaque cercle décrit les normales contenues dans un plan principal. Une normale 3D quelconque produit un point dans la région admissible entre les cercles, pas forcément sur une circonférence.</p><p>La contrainte de von Mises mesure la partie déviatorique. Une pression hydrostatique déplace les trois valeurs de la même quantité sans changer von Mises ni les rayons. Un état hydrostatique peut néanmoins intervenir dans d’autres modes de rupture ; von Mises n’est pas un critère universel.</p>',formula:'σVM = √{[(σ1−σ2)² + (σ2−σ3)² + (σ3−σ1)²]/2}\nτmax,3D = (σ1−σ3)/2'},
    {title:'Vérifier le cordon',subtitle:'Gorge & Eurocode 3',badge:'Analyste des assemblages',icon:'△',time:'20 min',
      lesson:'<p>Dans une soudure d’angle, travaille dans le <b>plan de gorge</b> : σ⊥ est normale à la gorge ; τ⊥ est dans la gorge, perpendiculaire au cordon ; τ∥ est dans la gorge, parallèle au cordon. La gorge efficace a diffère de la jambe z ; pour un cordon idéal à 45°, a = z/√2.</p><p>La méthode directionnelle de EN 1993-1-8:2005 §4.5.3.2 vérifie deux inégalités. Les exercices donnent fu (pièce assemblée la plus faible), βw et γM2. Le taux d’utilisation est le maximum des deux rapports.</p><p>Les exemples portent sur la résistance statique locale avec contraintes de calcul déjà établies. Ils ne vérifient pas à eux seuls la géométrie, la longueur efficace, le métal de base, la fatigue ou l’exécution.</p>',formula:'√[σ⊥² + 3(τ⊥² + τ∥²)] ≤ fu/(βw γM2)\nσ⊥ ≤ 0,9 fu/γM2'},
    {title:'Penser en ingénieur',subtitle:'Synthèse & choix du modèle',badge:'Prêt pour la synthèse',icon:'✧',time:'20 min',
      lesson:'<p>Commence chaque dossier par le repère, les unités, le chargement et les hypothèses. Passe des efforts au tenseur, puis aux invariants et au critère adapté. Termine par une conclusion limitée à ce que tu as réellement vérifié.</p><p>La résistance statique d’un cordon relève ici de l’Eurocode 3. La fatigue dépend notamment de l’étendue des contraintes, du nombre de cycles et du détail constructif. La qualité des imperfections de soudage (ISO 5817:2023) et les exigences d’exécution (EN 1090-2+A1:2024) ont des rôles différents.</p><p>Les cas sont des situations industrielles reconstruites : tôle de charpente, gousset, rosette près d’un joint et zone bridée. Les valeurs sont pédagogiques, sans procès-verbal de mesure ni qualification officielle IWE.</p>',formula:'Efforts → tenseur → changement de repère → critère → conclusion'},
  ];
  const num=(label,answer,unit='MPa',extra={})=>({label,answer,unit,...extra});
  const choice=(label,options,answer)=>({label,options,answer,unit:''});
  const tensor=(x,y,t,z=0)=>[[x,t,0],[t,y,0],[0,0,z]];
  function exercise(id,seed=0){
    const k=1+(Math.abs(seed)%4)*0.2,x=120*k,y=40*k,t=30*k,p=M.principal2(x,y,t);
    const base={id,chapter:Math.floor(id/3),reference:'Mécanique des milieux continus · petites déformations',scene:'plate'};
    let q;
    switch(id){
      case 0:q={title:'Une matrice à compléter',...withMatrix('context','Au voisinage d’un joint bout à bout :','σ',[[x,t,0],['?',y,0],[0,0,0]],'MPa','Le milieu ne transmet pas de couples internes.'),fields:[num('Composante σyx manquante',t)],hint:'L’équilibre en rotation rend le tenseur symétrique.',explanation:'σyx = σxy. Les deux termes hors diagonale décrivent des cisaillements sur des faces différentes, liés par l’équilibre.'};break;
      case 1:q={title:'Des kN aux MPa',context:`Une tôle soudée bout à bout de largeur 80 mm et d’épaisseur 10 mm porte un effort axial de ${fmt(96*k)} kN. On étudie la section courante, loin des concentrations de contraintes.`,fields:[num('Contrainte normale nominale σx',x)],hint:'A = largeur × épaisseur. Convertis les kN en N.',explanation:`A = 800 mm² ; N = ${fmt(96000*k)} N ; σx = N/A = ${fmt(x)} MPa. La traction est positive.`};break;
      case 2:q={title:'La face raconte une colonne',...withMatrix('context','On reprend le tenseur :','σ',tensor(x,y,t),'MPa','La normale de la coupe est n = (1, 0, 0).'),fields:[num('Composante tx du vecteur contrainte',x),num('Composante ty du vecteur contrainte',t)],hint:'Multiplie la matrice par n. Ici, cela sélectionne la première colonne.',explanation:`t = σn = (${fmt(x)}, ${fmt(t)}, 0) MPa. tx est normale à cette face, ty est tangentielle.`};break;
      case 3:{const a=100*k;q={title:'La coupe à 45°',context:`Une tôle sous traction uniaxiale σx = ${fmt(a)} MPa est coupée selon une normale tournée de +45°. σy = τxy = 0.`,fields:[num('Contrainte normale σn',a/2),num('Cisaillement signé τx′y′',-a/2)],hint:'À 45°, cos 2θ = 0 et sin 2θ = 1. La direction y′ vaut (−sin θ, cos θ).',explanation:`σn = ${fmt(a/2)} MPa et τx′y′ = ${fmt(-a/2)} MPa. Le signe provient de la projection sur y′, pas de l’intensité de la traction.`};break;}
      case 4:{const r=M.rotate2(x,y,t,30);q={title:'Tourner sans changer l’état',context:`Près d’un gousset soudé, σx = ${fmt(x)}, σy = ${fmt(y)}, τxy = ${fmt(t)} MPa. Tourne le repère de +30°.`,fields:[num('σx′',r.x),num('τx′y′',r.xy)],hint:'Calcule C et D, puis utilise cos 60° et sin 60°.',explanation:`C = ${fmt((x+y)/2)}, D = ${fmt((x-y)/2)}. σx′ = C + D cos 60° + τxy sin 60° = ${fmt(r.x)} ; τx′y′ = −D sin 60° + τxy cos 60° = ${fmt(r.xy)} MPa.`};break;}
      case 5:q={title:'Le contrôle qui ne tourne pas',context:`Le même état a σx = ${fmt(x)}, σy = ${fmt(y)}, σz = 0 MPa. Après rotation dans xy, combien vaut σx′ + σy′ ?`,fields:[num('Trace dans le plan',x+y),choice('La rotation physique du repère de +20° déplace A sur notre cercle de…',['+20°','−40°','+40°'],'−40°')],hint:'La trace est un invariant. L’axe τ est positif vers le haut dans ce jeu.',explanation:'La somme des contraintes normales reste identique. Avec notre convention de cisaillement, le point tourne de −2θ sur le cercle.'};break;
      case 6:q={title:'Trouver le centre et le rayon',context:`Le point matériel d’une tôle soudée porte σx = ${fmt(x)}, σy = ${fmt(y)}, τxy = ${fmt(t)} MPa. Construis son cercle de Mohr.`,fields:[num('Centre C',p.center),num('Rayon R',p.radius)],hint:'C est la moyenne des normales ; R est l’hypoténuse formée par leur demi-différence et le cisaillement.',explanation:`C = (${fmt(x)} + ${fmt(y)})/2 = ${fmt(p.center)} ; R = √[${fmt((x-y)/2)}² + ${fmt(t)}²] = ${fmt(p.radius)} MPa.`};break;
      case 7:q={title:'Faire disparaître le cisaillement',context:`Pour σx = ${fmt(x)}, σy = ${fmt(y)}, τxy = ${fmt(t)} MPa, recherche les valeurs principales du plan et la normale associée à la plus grande.`,fields:[num('σmax du plan',p.max),num('σmin du plan',p.min),num('θp, normale de σmax',p.angle,'°',{angle:true})],hint:'Prends C ± R. Pour le bon quadrant de l’angle, utilise atan2(2τxy, σx−σy), puis divise par deux.',explanation:`C ± R = ${fmt(p.max)} et ${fmt(p.min)} MPa. θp = ${fmt(p.angle)}° modulo 180°. Sur cette face τx′y′ = 0.`};break;
      case 8:q={title:'Le zéro qu’on oublie',context:`Une tôle mince présente les valeurs principales du plan ${fmt(150*k)} et ${fmt(50*k)} MPa. L’état est en contraintes planes.`,fields:[num('Cisaillement maximal dans le plan',50*k),num('Cisaillement maximal absolu en 3D',75*k)],hint:'En 3D, insère σz = 0 parmi les valeurs principales avant de prendre les extrêmes.',explanation:`Dans xy : (${fmt(150*k)}−${fmt(50*k)})/2 = ${fmt(50*k)}. En 3D : (${fmt(150*k)}−0)/2 = ${fmt(75*k)} MPa.`};break;
      case 9:q={title:'Le piège du facteur deux',context:`Une mesure près d’un cordon donne γxy = ${fmt(800*k)} µrad. Remplis le terme hors diagonale du tenseur des petites déformations.`,fields:[num('εxy',400*k,'µε')],hint:'Le cisaillement d’ingénieur vaut deux fois le terme tensoriel.',explanation:`εxy = γxy/2 = ${fmt(400*k)} µε. Dans le cercle, l’ordonnée est γ/2, jamais γ directement.`};break;
      case 10:{const a=M.principal2(600*k,-200*k,300*k);q={title:'Un cercle pour les déformations',context:`À la surface d’une pièce soudée : εx = ${fmt(600*k)} µε, εy = ${fmt(-200*k)} µε et γxy = ${fmt(600*k)} µrad.`,fields:[num('Déformation principale maximale du plan',a.max,'µε'),num('γmax dans le plan',2*a.radius,'µrad')],hint:'Entre γxy/2 dans le tenseur. Le rayon du cercle vaut ensuite γmax/2.',explanation:`Cε = ${fmt(a.center)} µε ; Rε = ${fmt(a.radius)} µε ; εmax = ${fmt(a.max)} µε et γmax = ${fmt(2*a.radius)} µrad.`};break;}
      case 11:q={title:'Décoder une rosette',context:`Une rosette compensée en température, près d’un joint bout à bout, mesure ε0 = ${fmt(600*k)}, ε45 = ${fmt(400*k)}, ε90 = ${fmt(-100*k)} µε.`,fields:[num('γxy',300*k,'µrad'),num('εxy',150*k,'µε')],hint:'Utilise la transformation à 45° : ε45 = (εx+εy)/2 + γxy/2.',explanation:`γxy = 2ε45−ε0−ε90 = ${fmt(300*k)} µrad. La matrice contient εxy = ${fmt(150*k)} µε.`};break;
      case 12:{const e=M.strain(tensor(x,y,t));q={title:'La loi de Hooke en action',context:`Acier isotrope : E = 210 000 MPa, ν = 0,30 ; σx = ${fmt(x)}, σy = ${fmt(y)}, τxy = ${fmt(t)}, σz = 0 MPa.`,fields:[num('εx',e[0][0]*1e6,'µε'),num('γxy',2*e[0][1]*1e6,'µrad')],hint:'εx = (σx−νσy)/E ; γxy = 2(1+ν)τxy/E. Convertis ensuite en micro-unités.',explanation:`εx = ${fmt(e[0][0]*1e6)} µε ; G = 80 769,231 MPa ; γxy = ${fmt(2*e[0][1]*1e6)} µrad.`};break;}
      case 13:q={title:'Deux hypothèses, deux réponses',context:`σx = ${fmt(x)} et σy = ${fmt(y)} MPa ; E = 210 000 MPa, ν = 0,30. Pas de déformation thermique. Compare une tôle mince en contraintes planes et une zone idéale en déformations planes (εz = 0).`,fields:[num('εz de la tôle mince',-0.3*(x+y)/210000*1e6,'µε'),num('σz de la zone en déformations planes',0.3*(x+y))],hint:'Dans le premier cas σz = 0. Dans le second, impose εz = [σz−ν(σx+σy)]/E = 0.',explanation:`Contraintes planes : εz = ${fmt(-0.3*(x+y)/210000*1e6)} µε. Déformations planes : σz = ν(σx+σy) = ${fmt(0.3*(x+y))} MPa.`};break;
      case 14:q={title:'Chauffer une pièce bridée',context:`Une barre soudée est totalement bloquée axialement mais libre latéralement. ΔT = +${fmt(40*k)} K, α = 12 × 10⁻⁶/K, E = 210 000 MPa. On reste dans un modèle élastique uniaxial.`,fields:[num('σx thermique',-210000*12e-6*40*k),choice('Cette estimation prédit-elle seule les contraintes résiduelles d’un cycle complet de soudage ?',['Oui','Non'],'Non')],hint:'εtotale = σx/E + αΔT = 0. La dilatation empêchée produit une compression.',explanation:`σx = −EαΔT = ${fmt(-210000*12e-6*40*k)} MPa. Un cycle réel requiert aussi l’histoire thermique et les mécanismes inélastiques.`};break;
      case 15:q={title:'Les trois cercles du joint bridé',context:`Dans la base principale d’une zone bridée, σ1 = ${fmt(180*k)}, σ2 = ${fmt(60*k)}, σ3 = ${fmt(-60*k)} MPa.`,fields:[num('Rayon R13',120*k),num('Rayon R12',60*k),num('Rayon R23',60*k),num('Contrainte de von Mises',Math.sqrt(43200)*k)],hint:'Chaque rayon est une demi-différence. Von Mises combine les trois différences au carré.',explanation:`R13 = ${fmt(120*k)} ; R12 = R23 = ${fmt(60*k)} MPa. σVM = √[(120²+120²+240²)/2] × ${fmt(k)} = ${fmt(Math.sqrt(43200)*k)} MPa.`};break;
      case 16:q={title:'Un tenseur entièrement couplé',...withMatrix('context','Une extraction de calcul local, dans une zone soudée bridée, donne :','σ',[[100*k,20*k,20*k],[20*k,100*k,20*k],[20*k,20*k,100*k]],'MPa'),fields:[num('σ1',140*k),num('σ2',80*k),num('σ3',80*k)],hint:'Le vecteur (1,1,1) est une direction propre. Dans son plan orthogonal, les deux autres valeurs sont identiques.',explanation:`σ(1,1,1) = ${fmt(140*k)}(1,1,1). Le tenseur s’écrit ${fmt(80*k)}I + ${fmt(20*k)}J, avec J rempli de 1 : les deux autres valeurs valent ${fmt(80*k)} MPa.`};break;
      case 17:q={title:'Ajouter de la pression',context:`Un état possède σ1 = ${fmt(140*k)}, σ2 = σ3 = ${fmt(80*k)} MPa. On ajoute −${fmt(50*k)} MPa à chaque composante diagonale.`,fields:[num('Nouveau τmax,3D',30*k),num('Nouveau σVM',60*k),choice('Les rayons des cercles…',['augmentent','restent identiques','diminuent'],'restent identiques')],hint:'Une translation hydrostatique laisse les différences de valeurs principales inchangées.',explanation:`τmax = (${fmt(140*k)}−${fmt(80*k)})/2 = ${fmt(30*k)} MPa ; σVM = ${fmt(60*k)} MPa. Seuls les centres se déplacent.`};break;
      case 18:{const w=M.weld(120*k,60*k,40*k,470,0.9,1.25);q={title:'Le contrôle directionnel',scene:'weld',reference:'EN 1993-1-8:2005 §4.5.3.2 · paramètres donnés',context:`Gorge d’un cordon d’angle : σ⊥ = ${fmt(120*k)}, τ⊥ = ${fmt(60*k)}, τ∥ = ${fmt(40*k)} MPa. On donne fu = 470 MPa, βw = 0,90, γM2 = 1,25. Contraintes de calcul à l’ELU, chargement statique.`,fields:[num('Sollicitation combinée',w.combined),num('Limite combinée',w.limitCombined),num('Limite normale',w.limitNormal)],hint:'Le coefficient 3 porte sur les deux cisaillements. La seconde limite n’utilise pas βw.',explanation:`√[σ⊥²+3(τ⊥²+τ∥²)] = ${fmt(w.combined)} MPa ; limite combinée = 417,778 MPa ; limite normale = 338,4 MPa. Les deux contrôles passent ici.`};break;}
      case 19:q={title:'Le second verrou',scene:'weld',reference:'EN 1993-1-8:2005 §4.5.3.2',context:'Gorge en traction : σ⊥ = 380 MPa, τ⊥ = τ∥ = 0. fu = 470 MPa, βw = 0,90, γM2 = 1,25. La première limite vaut 417,778 MPa.',fields:[num('Taux d’utilisation du critère normal',380/338.4,'',{tolerance:0.005}),choice('Conclusion sur les deux contrôles locaux',['Les deux passent','Le critère normal échoue','Le critère combiné échoue'],'Le critère normal échoue')],hint:'Compare 380 MPa à 0,9fu/γM2, même si la sollicitation combinée est acceptable.',explanation:'380/338,4 = 1,123 > 1 : le critère normal échoue. Une vérification unique avec la contrainte combinée aurait donné une conclusion erronée.'};break;
      case 20:q={title:'Dimensionner la gorge efficace',scene:'weld',reference:'EN 1993-1-8:2005 · méthode directionnelle, cisaillement pur',context:`Deux cordons parallèles identiques transmettent au total ${fmt(120*k)} kN par cisaillement longitudinal pur, réparti uniformément. Chaque longueur efficace est 100 mm. fu = 470 MPa, βw = 0,90, γM2 = 1,25.`,fields:[num('Gorge minimale issue du seul calcul de résistance',120000*k/(200*(470/(Math.sqrt(3)*0.9*1.25))),'mm',{tolerance:0.02})],hint:'τ∥ = F/(2aℓeff). La limite de cisaillement pur est fu/(√3 βw γM2).',explanation:`a ≥ F√3 βw γM2/(2ℓeff fu) = ${fmt(120000*k*Math.sqrt(3)*0.9*1.25/(200*470))} mm. Il reste à choisir une dimension constructible et vérifier toutes les dispositions géométriques.`};break;
      case 21:{const vm=M.vonMises(tensor(x,y,t));q={title:'Une tôle, plusieurs critères',context:`Section courante près d’une soudure bout à bout : σx = ${fmt(x)}, σy = ${fmt(y)}, τxy = ${fmt(t)}, σz = 0 MPa. On donne fy = 355 MPa et γM0 = 1. Hypothèse élastique, sans concentration locale ni instabilité.`,fields:[num('Contrainte de von Mises',vm),num('Taux d’utilisation élastique du métal de base',vm/355,'',{tolerance:0.005}),choice('Ce calcul suffit-il à vérifier un cordon d’angle ?',['Oui','Non'],'Non')],hint:'En contraintes planes, σVM² = σx²−σxσy+σy²+3τxy². Distingue métal de base et gorge du cordon.',explanation:`σVM = ${fmt(vm)} MPa ; taux = ${fmt(vm/355)}. La vérification locale du métal de base ne remplace pas celle de la gorge d’un cordon d’angle.`};break;}
      case 22:q={title:'Le pont reprend du service',context:`Au droit d’un détail soudé de pont, la contrainte normale nominale varie de ${fmt(-20*k)} à ${fmt(100*k)} MPa. On ne dispose ni de catégorie de détail ni de nombre de cycles.`,fields:[num('Étendue Δσ',120*k),choice('Peut-on conclure à la tenue en fatigue ?',['Oui, si σmax < fy','Non, il manque le détail et les cycles'],'Non, il manque le détail et les cycles')],hint:'L’étendue est maximum moins minimum, y compris quand le minimum est négatif.',explanation:`Δσ = ${fmt(100*k)}−(${fmt(-20*k)}) = ${fmt(120*k)} MPa. Une étude selon EN 1993-1-9 nécessite le détail, les cycles et les autres paramètres de vérification.`,reference:'EN 1993-1-9 · contexte fatigue, aucun dimensionnement complet'};break;
      case 23:q={title:'Le bon document au bon moment',context:'Un atelier livre un gousset soudé de charpente. Tu dois distinguer qualité de fabrication, exécution et résistance mécanique.',fields:[choice('Quel texte décrit les niveaux B, C, D d’imperfections ?',['ISO 5817:2023','EN 1993-1-8:2005','EN 1090-2+A1:2024'],'ISO 5817:2023'),choice('Un niveau B valide-t-il à lui seul la résistance ?',['Oui','Non'],'Non'),choice('Quel texte concerne l’exécution des structures en acier ?',['ISO 5817:2023','EN 1090-2+A1:2024'],'EN 1090-2+A1:2024')],hint:'La qualité d’une soudure et la résistance d’un assemblage répondent à deux questions distinctes.',explanation:'ISO 5817 traite des imperfections, avec B comme niveau le plus exigeant. EN 1090-2+A1 traite de l’exécution. La résistance doit être calculée avec les règles applicables à l’assemblage.',reference:'ISO 5817:2023 · EN 1090-2+A1:2024'};break;
      default:throw new Error('Défi inconnu');
    }
    return {...base,...q};
  }
  function exam(seed=0){
    const k=1+(Math.abs(seed)%7)*0.1;
    const a=[[160*k,40*k,0],[40*k,100*k,0],[0,0,40*k]],ev=M.principal3(a),e=M.strain(a);
    const ex=600*k*1e-6,ey=-100*k*1e-6,g=300*k*1e-6,E=210000,nu=0.3;
    const sx=E*(ex+nu*ey)/(1-nu*nu),sy=E*(ey+nu*ex)/(1-nu*nu),tau=E*g/(2*(1+nu));
    const r=M.rotate2(180*k,60*k,40*k,45),w=M.weld(r.x,r.xy,30*k,470,0.9,1.25);
    return [
      {title:'Dossier A · Zone soudée bridée',chapter:5,scene:'plate',reference:'Élasticité isotrope · état local reconstruit',
        ...withMatrix('context','Une extraction d’un modèle élastique local donne :','σ',a,'MPa','E = 210 000 MPa, ν = 0,30. Détermine les valeurs principales, le plus grand cercle, von Mises et la déformation axiale. Aucune qualification du modèle thermomécanique n’est demandée.'),
        fields:[num('σ1',ev[0]),num('σ2',ev[1]),num('σ3',ev[2]),num('τmax,3D',(ev[0]-ev[2])/2),num('σVM',M.vonMises(a)),num('εx',e[0][0]*1e6,'µε')],
        explanation:`Diagonaliser le bloc xy donne ${fmt(ev[0])} et ${fmt(ev[1])} MPa ; σz = ${fmt(ev[2])} MPa est la troisième valeur. Trier, prendre (σ1−σ3)/2, puis les différences pour von Mises. εx = [σx−ν(σy+σz)]/E = ${fmt(e[0][0]*1e6)} µε.`},
      {title:'Dossier B · Rosette sur une tôle soudée',chapter:4,scene:'plate',reference:'Petites déformations · contraintes planes',
        context:`Rosette 0°/45°/90° compensée en température : ε0 = ${fmt(600*k)}, ε45 = ${fmt(400*k)}, ε90 = ${fmt(-100*k)} µε. Acier isotrope, E = 210 000 MPa, ν = 0,30. Surface libre : σz = τxz = τyz = 0. Retrouve le tenseur de contrainte et la contraction hors plan.`,
        fields:[num('γxy',g*1e6,'µrad'),num('σx',sx),num('σy',sy),num('τxy',tau),num('εz',-nu*(sx+sy)/E*1e6,'µε'),choice('Peut-on imposer en plus εz = 0 ?',['Oui','Non'],'Non')],
        explanation:`γxy = 2ε45−ε0−ε90. σx = E(εx+νεy)/(1−ν²) ; σy = E(εy+νεx)/(1−ν²) ; τxy = Gγxy. Convertir les micro-unités en 10⁻⁶ avant multiplication par E. εz = −ν(σx+σy)/E, donc contraintes planes ne signifie pas déformations planes.`},
      {title:'Dossier C · Gorge de cordon à 45°',chapter:6,scene:'weld',reference:'EN 1993-1-8:2005 §4.5.3.2 · paramètres imposés',
        context:`Dans une section perpendiculaire au cordon, σx = ${fmt(180*k)}, σy = ${fmt(60*k)}, τxy = ${fmt(40*k)} MPa. La normale à la gorge fait +45° avec x. Le cisaillement longitudinal de gorge vaut ${fmt(30*k)} MPa, fourni séparément. Contraintes de calcul, statiques et uniformes ; fu = 470 MPa, βw = 0,90, γM2 = 1,25. Calcule les deux rapports et conclus uniquement sur ces deux contrôles.`,
        fields:[num('σ⊥',r.x),num('τ⊥ signé',r.xy),num('Sollicitation combinée',w.combined),num('Rapport combiné',w.ratioCombined,'',{tolerance:0.005}),num('Rapport normal',w.ratioNormal,'',{tolerance:0.005}),choice('Les deux contrôles locaux sont-ils satisfaits ?',['Oui','Non'],w.pass?'Oui':'Non')],
        explanation:`Rotation de +45° : σ⊥ = ${fmt(r.x)} MPa ; τ⊥ = ${fmt(r.xy)} MPa. Inclure aussi τ∥ dans √[σ⊥²+3(τ⊥²+τ∥²)]. Diviser par 417,778 MPa, puis σ⊥ par 338,4 MPa. Les deux rapports doivent être ≤ 1. Il reste d’autres vérifications pour l’assemblage complet.`},
    ];
  }
  function grade(q,values){return q.fields.map((f,i)=>f.options?values[i]===f.answer:M.matches(values[i],f.answer,f));}
  return {chapters,exercise,exam,grade,fmt};
});
